import type { Template, Snippet } from '@card-architect/schemas';

export const defaultTemplates: Template[] = [
  {
    id: 'tpl-anime-character',
    name: 'Anime Character',
    description: 'Full card template for anime-style characters with expressive personality',
    category: 'character',
    targetFields: 'all',
    content: {
      description: '**Appearance:**\n[Physical description - hair, eyes, height, build, distinguishing features]\n\n**Background:**\n[Character history and origin]\n\n**Occupation:**\n[Role or job]',
      personality: '**Core Traits:**\n- [Trait 1]\n- [Trait 2]\n- [Trait 3]\n\n**Quirks:**\n- [Unique behavior or habit]\n\n**Speech Pattern:**\n[How they talk, catchphrases, verbal tics]',
      scenario: '{{user}} encounters {{char}} at [location]. [Current situation or conflict].',
      first_mes: '*[Action or expression]* \n\n"[Dialogue introducing themselves]"',
      mes_example: '<START>\n{{user}}: [Example user message]\n{{char}}: *[Action]* "[Response showing personality]"\n\n<START>\n{{user}}: [Another example]\n{{char}}: "[Response with catchphrase or quirk]"',
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    isDefault: true,
  },
  {
    id: 'tpl-realistic-roleplay',
    name: 'Realistic Roleplay',
    description: 'Grounded, realistic character template with detailed psychology',
    category: 'character',
    targetFields: 'all',
    content: {
      description: '**Physical Description:**\n[Age, appearance, clothing style]\n\n**Background:**\n[Upbringing, education, life experiences]\n\n**Current Situation:**\n[Living situation, occupation, relationships]',
      personality: '**Personality:**\n[Detailed psychological profile]\n\n**Strengths:**\n- [Strength 1]\n- [Strength 2]\n\n**Flaws:**\n- [Flaw 1]\n- [Flaw 2]\n\n**Motivations:**\n[What drives them]',
      scenario: '[Detailed scenario context explaining the relationship between {{char}} and {{user}}, the setting, and current circumstances]',
      first_mes: '[Natural, realistic greeting that establishes the scene and character\'s current emotional state]',
      mes_example: '{{user}}: [Realistic user message]\n{{char}}: [Natural response showing character\'s communication style and thought process]',
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    isDefault: true,
  },
  {
    id: 'tpl-adventure-guide',
    name: 'Adventure Guide/NPC',
    description: 'Template for adventure scenarios and game-like NPCs',
    category: 'scenario',
    targetFields: 'all',
    content: {
      description: '**Role:** [Guide/Merchant/Quest Giver]\n\n**Appearance:**\n[Distinctive features that fit the setting]\n\n**Expertise:**\n[Special knowledge or skills]',
      personality: '**Demeanor:** [How they interact with adventurers]\n\n**Knowledge Base:** [What they know about the world]\n\n**Goals:** [What they want from interactions]',
      scenario: 'The world of [setting name]. {{char}} serves as [role] in [location]. {{user}} is [adventurer/traveler/etc].',
      first_mes: '*{{char}} [action showing their role]*\n\n"[Greeting that hints at available information or services]"',
      mes_example: '<START>\n{{user}}: "What can you tell me about this area?"\n{{char}}: "[Informative response with world-building details]"\n\n<START>\n{{user}}: "[Request for help]"\n{{char}}: "[Response showing expertise and personality]"',
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    isDefault: true,
  },
  {
    id: 'tpl-detailed-personality',
    name: 'Detailed Personality Structure',
    description: 'In-depth personality template with psychological framework',
    category: 'character',
    targetFields: ['personality'],
    content: {
      personality: '**Core Personality:**\n[MBTI or similar framework if applicable]\n\n**Traits:**\n- Conscientiousness: [Level and description]\n- Openness: [Level and description]\n- Extraversion: [Level and description]\n- Agreeableness: [Level and description]\n- Neuroticism: [Level and description]\n\n**Values:**\n- [Core value 1]\n- [Core value 2]\n\n**Fears:**\n- [Deep fear 1]\n- [Deep fear 2]\n\n**Communication Style:**\n[How they express themselves]\n\n**Conflict Response:**\n[How they handle disagreements]',
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    isDefault: true,
  },
  {
    id: 'tpl-rich-scenario',
    name: 'Rich Scenario Template',
    description: 'Detailed scenario with world-building elements',
    category: 'scenario',
    targetFields: ['scenario'],
    content: {
      scenario: '**Setting:**\n[Time period, location, world type]\n\n**Current Situation:**\n[What is happening right now]\n\n**Relationship Context:**\n[How {{char}} and {{user}} know each other]\n\n**Active Conflicts:**\n- [Conflict 1]\n- [Conflict 2]\n\n**Goals:**\n- {{char}}\'s goal: [What they want]\n- {{user}}\'s goal: [What they might want]\n\n**Constraints:**\n[Rules, limitations, or obstacles in the scenario]',
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    isDefault: true,
  },
  {
    id: 'tpl-example-dialogue',
    name: 'Example Dialogue Format',
    description: 'Structured format for example dialogues',
    category: 'dialogue',
    targetFields: ['mes_example'],
    content: {
      mes_example: '<START>\n{{user}}: [Action or dialogue showing user personality]\n{{char}}: *[Character\'s physical reaction]* "[Verbal response with emotion]"\n\n<START>\n{{user}}: [Different type of interaction]\n{{char}}: [Character\'s response showing different facet of personality]\n\n<START>\n{{user}}: [Edge case or conflict situation]\n{{char}}: [How character handles difficult situations]',
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    isDefault: true,
  },
];

export const defaultSnippets: Snippet[] = [
  {
    id: 'snip-ooc-instruction',
    name: 'OOC Instruction',
    description: 'Out of character instruction format',
    category: 'instruction',
    content: '[OOC: {{char}} will never break character or acknowledge being an AI]',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    isDefault: true,
  },
  {
    id: 'snip-char-behavior',
    name: 'Character Behavior Rule',
    description: 'Specify how {{char}} should behave',
    category: 'instruction',
    content: '{{char}} will always [specific behavior or rule]',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    isDefault: true,
  },
  {
    id: 'snip-user-freedom',
    name: 'User Freedom',
    description: 'Clarify {{user}} autonomy',
    category: 'instruction',
    content: '{{user}} can be any gender, age, or personality. {{char}} will adapt to {{user}}\'s choices.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    isDefault: true,
  },
  {
    id: 'snip-divider',
    name: 'Section Divider',
    description: 'Visual separator for sections',
    category: 'format',
    content: '\n---\n',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    isDefault: true,
  },
  {
    id: 'snip-emphasis-bold',
    name: 'Bold Emphasis',
    description: 'Bold text for emphasis',
    category: 'format',
    content: '**text**',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    isDefault: true,
  },
  {
    id: 'snip-emphasis-italic',
    name: 'Italic Emphasis',
    description: 'Italic text for actions or thoughts',
    category: 'format',
    content: '*text*',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    isDefault: true,
  },
  {
    id: 'snip-placeholder-char',
    name: 'Character Placeholder',
    description: 'Insert {{char}} placeholder',
    category: 'format',
    content: '{{char}}',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    isDefault: true,
  },
  {
    id: 'snip-placeholder-user',
    name: 'User Placeholder',
    description: 'Insert {{user}} placeholder',
    category: 'format',
    content: '{{user}}',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    isDefault: true,
  },
  {
    id: 'snip-consent-notice',
    name: 'Consent Notice',
    description: 'Standard consent and boundaries instruction',
    category: 'instruction',
    content: '{{char}} will always respect boundaries and consent. {{char}} will stop any action if {{user}} expresses discomfort.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    isDefault: true,
  },
  {
    id: 'snip-no-meta',
    name: 'No Meta-commentary',
    description: 'Prevent breaking the fourth wall',
    category: 'instruction',
    content: '{{char}} will never provide meta-commentary about the roleplay or break the fourth wall.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    isDefault: true,
  },
];
